name: "Rust release"

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      CARGO_REGISTRY_TOKEN:
        required: true
      DOCKER_REGISTRY_USER:
        required: false
      DOCKER_REGISTRY_PASSWORD:
        required: false

env:
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/exec@6.0
            @semantic-release/git@10.0
            @codedependant/semantic-release-docker@4.1
            @timada/semantic-release-cargo@1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Put spec in env
        run: |
          pkg_spec=$(cat openapi.json)
          echo "pkg_spec=$pkg_spec" >> $GITHUB_ENV
      
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: timada-org/sdk
          event-type: released
          client-payload: '{"pkg_name": "cobase", "pkg_spec": ${{ toJson(env.pkg_spec) }}}'
