name: "Service docker"

on:
  workflow_call:
    inputs:
      packages:
        required: true
        type: string
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true

jobs:
  build:
    strategy:
      matrix:
        package: ${{ fromJson(inputs.packages) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish
        run: cargo publish --no-verify -p ${{ matrix.package }}
