name: "Ci"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: node_modules/.bin/semantic-release
