name: "Service docker"

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      push:
        default: true
        required: false
        type: boolean
    secrets:
      DOCKER_REGISTRY_USER:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Set up tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
          labels: |
            org.opencontainers.image.licenses=AGPL-3.0
            org.opencontainers.image.vendor=Timada
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: service-${{ runner.os }}-buildx-cache

      - name: Build and push image to container registry
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache to original location
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
