name: "Renovate"

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.1
        with:
          token: ${{ secrets.GH_TOKEN }}
