name: "Rust testing"

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test ${{ matrix.rust }}

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust (${{ matrix.rust }})
        uses: dtolnay/rust-toolchain@${{ matrix.rust }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GH_TOKEN }}

      - name: Check Format
        if: matrix.rust == 'stable'
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Clippy
        if: matrix.rust == 'stable'
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
