name: "Audit"

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

env:
  CARGO_INCREMENTAL: 0

jobs:
  auditable:
    if: "!startsWith(github.event.commits[0].message, 'chore(release): ')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-auditable,cargo-audit

      - uses: Swatinem/rust-cache@v2
        with:
          cache-bin: false
          save-if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/alpha", "refs/heads/beta", "refs/heads/rn"]'), github.ref) }}

      - run: |
          cargo auditable build --release
          cargo audit bin target/release/${{ inputs.name }}
