name: "Service release"

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Create config file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: .releaserc.yml
          write-mode: overwrite
          contents: |
            {
              plugins: [
                {
                  path: "@semantic-release/commit-analyzer",
                  preset: "conventionalcommits"
                },
                {
                  path: "@semantic-release/release-notes-generator",
                  preset: "conventionalcommits"
                },
                "@semantic-release/github",
                {
                  path: "@timada/semantic-release-cargo",
                  cargoPublish: false
                },
                {
                  path: "@semantic-release/exec",
                  prepareCmd: "cargo update"
                },
                {
                  path: "@semantic-release/git",
                  assets: [
                    "**/Cargo.toml",
                    "Cargo.lock"
                  ]
                }]
              }

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: 19
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
          extra_plugins: |
            @semantic-release/exec@6.0
            @semantic-release/git@10.0
            @timada/semantic-release-cargo@1.0
            conventional-changelog-conventionalcommits@6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
