name: "Service testing"

on:
  workflow_call:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        env:
          GOGC: 100
        with:
          args: --timeout 10m0s
          skip-pkg-cache: true
      - name: Run test
        run: go test -v ./...
  pnpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm --stream -r lint
      - run: pnpm --stream -r test
